breaking(build_snap.yaml): Rename `artifact-name` to `artifact-prefix`
canonical/data-platform-workflows pull request #142
Opened 2024-02-26 14:09 UTC by carlcsaposs-canonical

Support upcoming change to build snaps on multiple architectures

All other changes will be backwards-compatible; separated backwards-incompatible changes into different PR to better document which changes are incompatible

2024-02-26 17:36 UTC, dragomirp approved these changes

2024-02-27 08:24 UTC, taurus-forever requested changes
pgbouncer in latest/stable is not from us (legacy charm), we are using `1/stable`: https://charmhub.io/pgbouncer?channel=1/stable

Please update badges.

2024-02-27 09:57 UTC, taurus-forever commented
> @taurus-forever wrong pr?

Yes... See https://github.com/canonical/pgbouncer-operator/pull/165#pullrequestreview-1902862525  :-D

2024-02-27 09:58 UTC, taurus-forever approved these changes

2024-02-27 09:58 UTC, merged